[tool.poetry]
name = "myproject"
version = "0.1.0"
description = ""
authors = ["Step <stepnest02@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
flask = "3.1.2"
selenium = "4.37.0"
webdriver-manager = "4.0.2"
requests = "2.32.5"
